[tool.poetry]
name = "deduce"
version = "1.0.8"
description = "Deduce: de-identification method for Dutch medical text"
authors = ["Vincent Menger <vmenger@protonmail.com>"]
maintainers = ["Vincent Menger <vmenger@protonmail.com>"]
license = "GNU LGPLv3"
readme = "README.md"
repository = "https://github.com/vmenger/deduce/"
keywords = ["de-identification", "medical text", "dutch", "nlp"]
classifiers = [
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
include = ["deduce/data/*"]

[tool.poetry.dependencies]
python = "^3.9"
rapidfuzz = "^2.11.1"
docdeid = "0.1.0"
regex = "^2022.9.13"
deprecated = "^1.2.13"

[tool.poetry.dev-dependencies]
black = "^22.10.0"
isort = "^5.10.1"
pylint = "^2.15.4"
pytest = "^7.1.3"
pytest-cov = "^4.0.0"
flake8 = "^5.0.4"
flake8-annotations = "^2.9.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"