name: tests

on:
  push:
    branches:
    - master
    - next-release
  pull_request:
    branches:
    - master
    - next-release

jobs:

  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Test with pytest
      run: |
        make test
