name: tests

on:
  push:
    branches:
    - master
    - next-release
  pull_request:
    branches:
    - master
    - next-release

jobs:

  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Test with pytest
      run: |
        make test

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@1.1.3
      env:
        NODE_COVERALLS_DEBUG: 1
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        flag-name: py-${{ matrix.python-version }}
        path-to-lcov: coverage.lcov
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@1.1.3
      env:
        NODE_COVERALLS_DEBUG: 1
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        parallel-finished: true